### ISSUE TITLE
Add templates to init command

### ISSUE THREAD

**Issue by SheepFromHeaven** [biotope/biotope-cli#12]
**Is your feature request related to a problem? Please describe.**
I am lost i I run the init command and get a completely empty boilerplate. 

**Describe the solution you'd like**
As I'm new to biotope I would like to be able to generate a prefilled boilerplate

**Comment by jurekbarth** [comment]
@SheepFromHeaven from heaven i really like this idea, as it enhances developer experience. The serverless cli does something similar: `serverless create --template hello-world` i also like the "create" instead of "init" or maybe allow both with an alias?
