### ISSUE TITLE
Wrong filename in generated page

### ISSUE THREAD

**Issue by dweiger** [biotope/biotope-cli#47]
**Wrong filename in generated page**
The generated path in the page looks like:
contentMain="components/XHeroeNumber/scaffolding/**demo**"

But in the scaffolding folder a file with the component name is generated. 

**Expected behavior**
The CLI tool generates the path with the hbs filename:
contentMain="components/XHeroeNumber/scaffolding/**XHeroeNumber**"

**Comment by luke-m** [comment]
This is an issue with biotope/generator, thus it should be addressed there. I copied the content of this issue into a new one in the correct repo, [here](https://github.com/biotope/biotope-generator/issues/50).
