### ISSUE TITLE
Update link text for biotope.sh

### ISSUE THREAD

**Issue by rhafner** [biotope/biotope-cli#87]
**Is your feature request related to a problem? Please describe.**
Give people more information on what Biotope is and what benefits they can get from it.

**Describe the solution you'd like**
Please update the text in the readme and/or in the documentation with a similar text to this:

> Biotope, a toolchain for lasting design systems. 

> Biotope helps you to build, distribute and adopt a library of web components with a consistent design and of high quality across all your websites and apps. With Biotope you can easily collaborate with your team to develop and maintain the user interface of all your digital experiences from a single location.

> If you want to learn more about Biotope and how you can benefit from using this toolchain please visit https://biotope.sh

**Comment by IvailoStoyanov** [comment]
I just created A PR for this Issue:
https://github.com/biotope/biotope/pull/103
please have a look
